from . import account_invoice
from . import account_invoice_line
from . import account_product_fiscal_classification
from . import account_tax
from . import account_move_line
from . import product_pricelist
from . import product_pricelist_item
from . import product_product
from . import product_template
from . import res_company
from . import res_partner
