# Copyright (C) 2025 - Today: GRAP (http://www.grap.coop)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).
{
    "name": "GRAP odoo Business - All modules",
    "version": "16.0.1.0.0",
    "author": "GRAP",
    "maintainers": ["legalsylvain", "quentinDupont"],
    "developpment_status": "Production/Stable",
    "website": "https://github.com/grap/grap-odoo-business",
    "license": "AGPL-3",
    "depends": [
        "account_accountant_simple_settings",
        "account_invoice_supplierinfo_update_standard_price",
        "barcode_rule_per_company",
        "hr_direct_address_home",
        "mrp_bom_product_allergen",
        "mrp_product_price_quick_menus",
        "partner_hide_technical_abstract",
        "partner_hide_technical_company",
        "partner_hide_technical_employee",
        "partner_hide_technical_fix_calendar",
        "partner_hide_technical_fix_calendar_test",
        "partner_hide_technical_user",
        "product_food",
        "product_food_certification",
        "product_food_certification_account",
        "product_food_certification_sale",
        "product_food_certification_stock",
        "product_label",
        "product_label_mrp",
        "product_print_category_food_report",
        "product_standard_price_change_date",
        "recurring_consignment",
        "recurring_consignment_pos",
        "sale_eshop",
        "sale_recovery_moment",
    ],
}
